version: '3.8'

services:
  web:
    build: ./pruebatecno
    working_dir: /pruebatecno
    command: sh -c "python manage.py migrate && gunicorn pruebatecno.wsgi:application --bind 0.0.0.0:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/pruebadb
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: mytoken
      INFLUX_ORG: prueba
      INFLUX_BUCKET: metrics
      DEBUG: "False"
      PROM_RULES_PATH: /prometheus/alerts.yml
      NO_FILE_LOG: "1"
    user: "1000:1000"   # ajusta al UID:GID de tu usuario del host
    volumes:
      - ./pruebatecno:/pruebatecno
      - ./prometheus:/prometheus
    networks:
      - prueba
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
     

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pruebadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prueba
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:rw
      - ./prometheus/alerts.yml:/etc/prometheus/rules/alerts.yml:rw
    networks:
      - prueba
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
    ports:
      - "19090:9090"
    depends_on:
      - web

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml
    networks:
      - prueba
    command:
      - "--config.file=/alertmanager/alertmanager.yml"
    ports:
      - "19093:9093"

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: prueba
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - prueba

  grafana:
    image: grafana/grafana
    ports:
      - "13000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - prueba
    depends_on:
      - influxdb

volumes:
  postgres_data:
  influxdb_data:
  grafana_data:
  prometheus_data:

networks:
  prueba:
    driver: bridge