version: '3.8'

services:
  web:
    build: ./pruebatecno
    working_dir: /pruebatecno
    command: sh -c "python manage.py migrate && gunicorn pruebatecno.wsgi:application --bind 0.0.0.0:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/pruebadb
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: mytoken
      INFLUX_ORG: prueba
      INFLUX_BUCKET: metrics
      DEBUG: "False"
      PROM_RULES_PATH: /prometheus/alerts.yml
      NO_FILE_LOG: "1"
    user: "1000:1000"
    volumes:
      - ./pruebatecno:/pruebatecno
      - ./prometheus:/prometheus
    networks:
      - prueba
    expose:
      - "8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pruebadb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - prueba
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:rw
      - ./prometheus/alerts.yml:/etc/prometheus/rules/alerts.yml:rw
    networks:
      - prueba
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-lifecycle"
      - "--web.external-url=/prometheus"
      - "--web.route-prefix=/"
    expose:
      - "9090"
    depends_on:
      - web
      - system_metrics_exporter

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - prueba
    command: >
      --config.file=/etc/alertmanager/alertmanager.yml
      --web.external-url=http://localhost/alertmanager
      --web.route-prefix=/
    expose:
      - "9093"

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"   # publicado en host (para UI y escrituras externas)
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin123
      DOCKER_INFLUXDB_INIT_ORG: prueba
      DOCKER_INFLUXDB_INIT_BUCKET: metrics
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: mytoken
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - prueba

  grafana:
    image: grafana/grafana
    environment:
      GF_SERVER_ROOT_URL: "http://localhost/grafana/"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - prueba
    expose:
      - "3000"
    depends_on:
      - influxdb

  system_metrics_exporter:
    image: python:3.12-slim
    working_dir: /app
    command: sh -c "pip install prometheus_client psutil influxdb-client && python system-metrics/system_metrics_exporter.py"
    environment:
      EXPORTER_PORT: "9153"
      INTERVAL_SECS: "5"
      ENABLE_INFLUX_WRITE: "1"
      INFLUX_URL: "http://influxdb:8086"
      INFLUX_TOKEN: "mytoken"
      INFLUX_ORG: "prueba"
      INFLUX_BUCKET: "metrics"
    volumes:
      - ./system-metrics:/app/system-metrics:ro
    networks:
      - prueba
    expose:
      - "9153"
    depends_on:
      - influxdb

  nginx:
    image: nginx:1.25-alpine
    depends_on:
      web:
        condition: service_started
      grafana:
        condition: service_started
      prometheus:
        condition: service_started
      alertmanager:
        condition: service_started
    networks:
      - prueba
    ports:
      - "80:80"
      # - "443:443"  # si habilitas TLS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro  


volumes:
  postgres_data:
  influxdb_data:
  grafana_data:

networks:
  prueba:
    driver: bridge