groups:
- name: django-managed-alerts
  rules:
  - alert: Alerta CPU
    annotations:
      summary: Alert Alerta CPU triggered
    expr: Uso_CPU < 90.0
    for: 1m
    labels:
      severity: critical
