groups:
- name: django-managed-alerts
  rules:
  - alert: Alerta unica RAM
    annotations:
      summary: Alert Alerta unica RAM triggered
    expr: Uso_RAM < 90.0
    for: 1m
    labels:
      severity: info
  - alert: Alerta CPU
    annotations:
      summary: Alert Alerta CPU triggered
    expr: Uso_CPU > 3.0
    for: 1m
    labels:
      severity: warning
  - alert: Alerta AM
    annotations:
      summary: Alert Alerta AM triggered
    expr: Uso_RAM > 5.0
    for: 30s
    labels:
      severity: warning
  - alert: alerta pm
    annotations:
      summary: Alert alerta pm triggered
    expr: Uso_CPU < 5.0 and Uso_RAM < 5.0
    for: 45s
    labels:
      severity: critical
