global:
  scrape_interval: 5s

rule_files:
  - "/prometheus/alerts.yml"

scrape_configs:
  - job_name: "django"
    # Scrape the Influx-only endpoint that exposes Uso_CPU/ RAM
    metrics_path: /metrics/influx/
    static_configs:
      - targets: ["web:8000"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
