global:
  scrape_interval: 5s

rule_files:
  - "/prometheus/alerts.yml"
  - "/etc/prometheus/rules/alerts.yml"

scrape_configs:
  - job_name: "django"
    metrics_path: /metrics/influx/
    static_configs:
      - targets: ["web:8000"]

  - job_name: "system_metrics"
    static_configs:
      - targets: ["system_metrics_exporter:9153"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
