global:
  scrape_interval: 5s

rule_files:
  - "/prometheus/alerts.yml"

scrape_configs:
  - job_name: "django"
    metrics_path: /metrics
    static_configs:
      - targets: ["web:8000"]

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
